# 서버포트
server:
  port: 8082

# database 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa_board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234!!
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true # jpa가 생성하는 sql 쿼리를 로그에 보여주는 설정
    hibernate:
      ddl-auto: create
      #?? ?? ? ??? ??? create -> update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
